### ISSUE TITLE
/weather maakoodin perusteella lippu-emoji

### ISSUE THREAD

**Issue by M4R774** [M4R774/bobweb2#103]
Python telegram botista löytyy valmiina tosi helposti noi maiden lippuemojit: 
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#map-a-slot-machine-dice-value-to-the-corresponding-symbols

Ennen: 

> new york, US
> 🕒 04:45 (UTC-05:00)
> 🌡 -0.6 °C (tuntuu -0.6 °C)
> 💨 0.89 m/s kaakosta
> ☁ puolipilvistä

Jälkeen:

> new york, 🇺🇸
> 🕒 04:45 (UTC-05:00)
> 🌡 -0.6 °C (tuntuu -0.6 °C)
> 💨 0.89 m/s kaakosta
> ☁ puolipilvistä

**Comment by Kaehaerae** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Code-snippets#generate-flag-emojis-from-country-codes Tässä vielä tarkempi linkki
