### ISSUE TITLE
or_command-funktion asettaminen .kumpi komennon taakse

### ISSUE THREAD

**Issue by Kaehaerae** [M4R774/bobweb2#131]
Funktio or_command tulee asettaa esimerkiksi komennon .kumpi taakse, jotta vai-valinta tapahtuu vain silloin, kun käyttäjä haluaa oikeasti apua maagiselta bob-kasipallolta.

**Comment by taturl** [comment]
Linkatun PR:n myötä uusi maaginen sana on **.vai** eli vai pisteen kanssa. Pelkkä vai ilman pistettä ei enää laukaise toimintoa.
