### ISSUE TITLE
Async refactor

### ISSUE THREAD

**Issue by M4R774** [M4R774/bobweb2#138]
Voisi tehdä oikeaoppisesti ton async homman, että api kutsut ei oo blockaavia jne. 

DOD: Kaikki hommat tietokannan ja API:en kanssa on async, eli esim. vaikka joku on kysynyt .sää, niin .vai on edelleen toiminnassa. Yksikkötestissä voisi kokeilla vaikka mockailla että api pyynnössä kestää 1s ja silti .vai toimii.

**Comment by Latemus** [comment]
Removed linking with branch #138_commands_async_refactor as it only addresses chat commands that have external calls and do not use database or other shared resources. As such, does not fully implement the requirement.

**Comment by M4R774** [comment]
Voiko tän jo sulkea @Latemus ?

**Comment by Latemus** [comment]
Nyt tän vois sanoa olevan done. Tietokantaliikenne ei ole asyncronista, mutta sillä ei ole tällä hetkellä väliä, kun kanta on kokoajan ladattuna muistiin. Käsittelee tällä hetkellä viesteijä niin, ettei edellinen async-käsittely blokkaa seuraavaa. Tossa olis varmasti vielä hiottavaa ja paranneltavaa, esimerkiksi voisi jokaisen eri chatin käsitellä eri säikeissä tms tai muuttaa toteutusta niin, että joitakin komentoja ei alotettaisi käsittelemään, ennen kuin aiempi käsittely on valmis.
