### ISSUE TITLE
LFG (looking for group) -ominaisuus

### ISSUE THREAD

**Issue by Persikkapepe** [M4R774/bobweb2#162]
Olisi vallan mukavaa ja toivottavasti hyödyllistä, jos jollain komennolla voisi laittaa itsensä LFG-tilaan, jossa määrittäisi mitä pelejä olisi valmis pelaamaan ja kuinka kauan. Esim:
- /lfg 2h, cs:go, mow, arma, hll

Sitten /lfg näkisi onko ketään etsimässä ryhmää jossain pelissä.
Joku toinen komento sitten ottaisi käyttäjän pois jonosta tai joku maksimi aikamäärä vähintään siivoisi LFG-jonon.

En tiedä miten käytännön ongelmat kuten standardoidut pelien nimet ratkotaan.

**Comment by Latemus** [comment]
(kirjotettu puhelimella)

User Story 1 P haluaa pelata CS
- P antaa botille ryhmässä komennon ".lfg cs"
- botti lähettää viestin kaikissa ryhmissä, missä lfg-komento on kytketty päälle: "Ryhmähaku aloitettu pelissä CS käyttäjän P toimesta. Liity komennolla /lfg -y cs"
- lisäksi viestin "[lfg] cs: 🟢" jonka botti pinnaa ryhmän viesteihin
- käyttäjä T on kiinnostunut ja lähettää viestin ".lfg -y cs"
- botti lähettää privaviestin ryhmän aloittajalle käyttäjä P jossa ilmoittaa T: liittyneen
- botti päivittää ryhmissä pinnaamansa viesti olemaan "[lfg] cs: 🟢🟢"
- kun ryhmä on täynnä tai aikaraja tulee täyteen tms botti poistaa jonoon liittyvät tilanneviestit


Muita vaihtoehtoisia ominaisuuksia:
- lfg komentoon limit-parametrin jonka jälkeen botti lähettää privaviestillä kaikille tiedon, että ryhmä täynnä
- lfg komentoon viesti-parametri, jonka botti lisää pinnattuun viestiin

SWOT:
S: hyvä ominaisuus usean eri ryhmän välillä peliseuran hakemiseen.
W: yhden ryhmän sisällä peukkuemojit pelitieduisteluviestiin ajaa melko paljon samaa asiaa
O: hyvä tilaisuus opetella Telegram Apia ja rakentaa hyvää infraa botille (botin viestin hallinta, pinnailu)
T: teknisesti monimutkainen toteutettava. Vaatii paljon kehitystyötä ja kärsivällisyyttä ominaisuuksien testaajilta. Oikealla TG-käyttäjällä tehtävät automaattiset E2E testit olisi tarpeen.
