### ISSUE TITLE
Päivän kysymyksen voittajien tilastointi

### ISSUE THREAD

**Issue by Persikkapepe** [M4R774/bobweb2#19]
Bobibotti voisi kerätä päivänkysmärin voittajan mielellään automaagisesti (häsärien tai muiden avulla en minä tiedä en minä ole mikään osaaja) tai jonkun komennon avulla vähintään.

**Comment by Quu-Ukko** [comment]
Otettu työn alle. Mulla on visiot Päivän kysymys -nettisivusta niin suunnittelen tän sitä silmällä pitäen

**Comment by M4R774** [comment]
What is the LE for this @Quu-Ukko ?

**Comment by Latemus** [comment]
Ehdotan seuraavaa:
- botti tunnistaa viestin, joka sisältää '#päivänkysymys' olemaan sen päivän kysymys.
    - jos ei ole arkipäivä => ei tapahdu mitään
    - jos saman päivän aikana on jo tullut viesti, joka tulkittu päivän kysymykseksi, botti ilmoittaa asiasta
    - Muissa tapauksissa => viestin lähettäjä merkitään edellisen päivän kysymyksen voittajaksi

Tähän yhdistettynä muutamat komennot, joilla voi hallita poikkeuksia ja muita. Komento voi vaikka olla '/päivänkysymys' ja/tai '/pk'
- '/päivänkysymys tänään' tai '/pk tänään joka on replynä viestiin merkitsee sen viestin päivän kysymykseksi
    - tarpeellinen esim tilanteessa, jossa hashtag on jäänyt viestistä pois tai joku on lähettänyt virheellisesti jo viestin joka sisältää '#päivänkysymys'
    - viestin editointi ei taida olla ns. normi update, niin tägin lisääminen jälkikäteen ei triggeraa normi "komentoputkea"
- '/pk kausi' tms antaa kyseisen kauden tiedot


Esimerkkiehdotus kannan rakenteesta:

- daily_qa_season:
    - start_date
    - end_date
    - season_number

- daily_qa
    - daily_qa_season fk daily_qa_season
    - date
    - qa_message_id
    - qa_winner fk *user_taulu*
    - reply_count (eri käyttäjien [ei kysyjä] määrä, jotka vastanneet vähintään yhdellä viestillä)

Pohdittavaa:
- Halutaanko päivän kysymyksen viestin sisältö ja mahd. kuvat ja muut liitteet tallentaa?
    - Itse näkisin mielekkäänä, jos kysymyksiä pystyisi selailemaan jälkikäteen tai botilta voisi vaikka kysyä komennolla '/pk 2022-09-13' sen päivän kysymyksen tiedot (itse kysymys, voittaja)
- Halutaanko kysymyksen vastaus tallentaa jotenkin? Tämä tosin vaatisi, että vastauksissa olisi aina jokin ennalta määrätty teksti, hashtag, tms sisässä, millä se voidaan tulkita vastaukseksi sen päivän kysymykseen
- Minkälaista mahdollista tilastoa olisi mielekästä kerätä päivän kysymyksistä? Reagtiot itse kysymykseen ja niiden perusteella parhaat pisteet saaneiden kysymysten listaus?
