### ISSUE TITLE
Yksikkötestit eivät ole täysin tilattomia

### ISSUE THREAD

**Issue by M4R774** [M4R774/bobweb2#206]
README.md:hen on lisätty: "aja oheinen komento. Jos testit epäonnistuvat puuttuvien taulujen takia, kokeile ajaa testit uudelleen. Jos testit epäonnistuvat jostain muusta syystä, poista `bobweb2/bobweb/web/db.sqlite3` tiedosto, ja ajat testit **kahdesti** uudelleen."

Toisin sanottuna, osa testeistä olettavat tietokannan olevan jonkinlaisessa tilassa. Hidastaa lähinnä projektin kanssa alkuun pääsyä täysin uudella tekijällä, kun testit alkuun epäonnistuvat.

**Comment by Latemus** [comment]
Komennolla `python bobweb/web/manage.py test bobweb/bob` saa ajettua tilattomasti (django test runner). Linkitetyssä haarassa päivitetty tuo projektin juuren readme.md ohjeisiin
