### ISSUE TITLE
/space ilmoittaa, kuinka pitkä aika laukaisuun on. 

### ISSUE THREAD

**Issue by M4R774** [M4R774/bobweb2#24]
Nykyään: 

> Seuraava SpaceX lähtö CSG-2 lähtee 28.01.2022 klo 01:11:00 (Helsinki)

Tulevaisuudessa: 

> Seuraava SpaceX laukaisu CSG-2 lähtee **7 päivän, 4 tunnin, 32 minuutin kuluttua** 28.01.2022 **klo 01:11** Suomen aikaa.

**Comment by Kaehaerae** [comment]
Jatkospeksi: 

- sana "lähtö" muokattava sanaan "laukaisu" 

- rivitettävä kolmelle riville seuraavalla tavalla: 

```
Seuraava SpaceX laukaisu CSG-2 lähtee 
7 päivän, 4 tunnin, 32 minuutin kuluttua 
28.01.2022 klo 01:11 Suomen aikaa.
```

**Comment by Persikkapepe** [comment]
Hyvää työtä pojat.

**Comment by Persikkapepe** [comment]
Mistä täällä voi jakaa peukkuja ja tähtiä ja tykkäyksiä teille
