### ISSUE TITLE
Helppo tapa kytkeä ominaisuuksia päälle/pois chäteistä

### ISSUE THREAD

**Issue by M4R774** [M4R774/bobweb2#50]
Tällä hetkellä /kuulutus on/off saa helposti säädettyä päälle pois. Jos sama toteutetaan kaikille muille featureille, niin tulee tosi paljon toistuvaa koodia. Pitäis joku kätevä systeemi, että sais pienellä vaivalla togglattua noita featureita.

**Comment by M4R774** [comment]
Uusi komento esim. `.kytke kuulutukset päälle` joka togglaa kyseisen ominaisuuden päälle pois. Mäppäys tietokannan kenttien ja featuren nimen välillä dictillä ja pythonin getattrin function avulla: https://stackoverflow.com/questions/9379249/access-django-models-fields-using-a-string-instead-of-dot-syntax

Samalla saisi kätevästi palautettua dictissä olevat komentojen nimet listana, jos yhtään mätchiä ei löydy.

**Comment by matiasautio** [comment]
Joku valikko ois kätevä. Saiskohan kyselystä tehtyä asetukset?
Esim. /settings pyytää Bobia listaamaan kaikki komennot jotka saa pois ja päälle pollin muodossa.
Vastaamalla saa valittua kytkeekö komentoja pois vai päälle.
/settings uudelleen ja Bob tallentaa vastaukset ja poistaa pollin.
Vain kysyjän vastaukset otetaan huomioon ja halutessa vain admin voi käyttää /settings-komentoa.

**Comment by M4R774** [comment]
> Uusi komento esim. `.kytke kuulutukset päälle` joka togglaa kyseisen ominaisuuden päälle pois. Mäppäys tietokannan kenttien ja featuren nimen välillä dictillä ja pythonin getattrin function avulla: [stackoverflow.com/questions/9379249/access-django-models-fields-using-a-string-instead-of-dot-syntax](https://stackoverflow.com/questions/9379249/access-django-models-fields-using-a-string-instead-of-dot-syntax)
> 
> Samalla saisi kätevästi palautettua dictissä olevat komentojen nimet listana, jos yhtään mätchiä ei löydy.

- ".kytke 1337 off", jossain moduulissa dict[("1337", "leet_enabled"), ("kuulutukset", "broadcast_enabled")]
