### ISSUE TITLE
Sähkönhinta tarkkailu

### ISSUE THREAD

**Issue by M4R774** [M4R774/bobweb2#53]
Olis kiva, jos sähkön hintaa voisi kysellä bobilta ja jopa asettaa hälytyksiä.

**Comment by Kaehaerae** [comment]
Tämä lienee paras ratkaisu https://marketdata.nordpoolgroup.com/docs/services/MarketData-DayAhead-v2/operations/AreaPrices?

Tunnukset voi tehdä vapaasti, lisäksi käsiksipääsy vaatii erillistä subscriptionia - maksullisuus epäselvä

**Comment by Kaehaerae** [comment]
https://data.fingrid.fi/open-data-api/#!/events-controller/getEventsJsonUsingGET Vai tämä?

**Comment by Kaehaerae** [comment]
Nord poolille lähetetty request, katsotaan mitä tapahtuu

**Comment by M4R774** [comment]
https://sahko.tk/
https://github.com/slehtonen/sahko.tk/blob/master/parse.php
`define ("NORDPOOL_URL", "http://www.nordpoolspot.com/api/marketdata/page/35?currency=,,EUR,EUR");`

**Comment by Kaehaerae** [comment]
"Automatic extraction of data from this website **and/or** use for commercial purposes is strictly prohibited under Nord Pool’s [terms & conditions](https://www.nordpoolgroup.com/link/26d0e874de384164a9e6e7a31ea7b0ae.aspx)." En kovin mielelläni lähtis rikkomaan kyseisiä sääntöjä :D 

Vastauksena kysymykseeni näiden hinnasta suoraan Nordpoolilta sain täysin tyhjän vastauksen: 

```
"Thank you for your interest in our Data Services.
 
Access to our market data is subscription based and information about the subscriptions, license options and pricing can be found here: https://www.nordpoolgroup.com/services/power-market-data-services/

Please let us know if you have any questions or if you are interested in subscribing and we will send you our General Terms and the order form to be completed."
```

**Comment by M4R774** [comment]
https://www.nordpoolgroup.com/api/marketdata/page/35 täällä on siis name ja value kentissä päivämäärä ja hinta.

**Comment by M4R774** [comment]
Voiko tämän sulkea? @Latemus

**Comment by Latemus** [comment]
@M4R774 Tuosta alkuperäisestä ehdotuksesta puuttuu vielä nuo hälytykset, niin sillä jätetty auki. Tehty siitä oma issuensa #221 niin tämä suljettu.
