### ISSUE TITLE
/users output näyttää hirveältä ja vaikeaselkoiselta

### ISSUE THREAD

**Issue by M4R774** [M4R774/bobweb2#73]

**Comment by matiasautio** [comment]
Lähdin kokeilemaan tätä Markdown ja html tableilla, mutta ne menee rikki puhelimella. Desktopilla näyttää ihan hyvältä.
Esim.
`<pre>| name | rank | prestige | messages |
|------|------|----------|----------|</pre>`

format() funktiolla saa nätin asettelun aikaiseksi esim. "{0:<20} {1} {2}".format(tähän, halutut, tekstit), mutta tämäkin menee Telegramissa rikki.

Ehkä yksinkertainen markdown tyylittely vois olla tarpeeks.
Esim.
**SakuLarsson** 70 **|** 2 **|** 420
**tatsoni** 72**|** 0 **|** 666

Kun ryhmän jäsenten nimet on eripituisia, numerot alkavat pakosti eri kohdasta riviä ja listaus näyttää sekavalta.
