### ISSUE TITLE
/help-komento, joka listaa bob-botin featuret

### ISSUE THREAD

**Issue by Kaehaerae** [M4R774/bobweb2#76]

**Comment by Latemus** [comment]
Komento lisätty.

**Comment by Latemus** [comment]
Asiakkaalta saatu palaute, että ei toimi halutusti => tiketti avattu uudelleen.
![image](https://user-images.githubusercontent.com/13104473/182918914-0fcd176c-38df-4137-be80-6068665e83a7.png)

Samalla voisi lisätä mahdollisuuden saada yksittäisistä komennoista enemmän informaatiota komennolla `/help [komento]`. Esim `/help kuulutus` antaisi vastauksen:
```
!kuulutus [ on | off ] 
  - on: kuulutukset päälle
  - off: kuulutukset pois päältä
  
Kytkee "kuulutukset" päälle tai pois aktiivisessa keskustelussa. Bob
esimerkiksi kuuluttaa aina uusimmat gitin commit viestit käynnistyessään. 
```

**Comment by Latemus** [comment]
![image](https://user-images.githubusercontent.com/13104473/189730995-8c7cf0a7-fc26-4cb5-9953-d6036b67750d.png)
Komento palauttaa nyt nätin listan puhelimellakin (Telegram-kirjaisinkoko oletus 16).
