### ISSUE TITLE
Ilmoitus uudesta ilmaisesta Epic Games pelistä

### ISSUE THREAD

**Issue by matiasautio** [M4R774/bobweb2#77]
Uusi ilmaispeli julkaistaan joka viikko torstaina 10 am est.
https://www.epicgames.com/store/en-US/free-games sivulta voi scrapee tuohon aikaan suoran linkin ilmaispelin Epic Games listaukseen.
Botin viestin sisältö:
- Pelin nimi
- Suora linkki peliin jotta helppo avata Epic Games -sovelluksella ja lisätä kirjastoon.

Nice to have:
- Pelin kuvaus jonka voisi vuorostaan scrapee pelin omalta sivulta.

Olen aiemmin käyttänyt tähän Beautiful Soupia. Muut ehdotukset tervetulleita!
https://realpython.com/beautiful-soup-web-scraper-python/

**Comment by matiasautio** [comment]
Scrapeeminen on hidasta (ja jossain kiellettyä), vaihto tällaseen apiin:
https://rapidapi.com/thekevinconnor@gmail.com/api/free-epic-games/

Hakuja saa olla 100 / kk.
Tuolta uusimman pelin hakeminen on helppoa, se tulee aina apilla saatavan listan viimeiseksi.
Tämä osa ominaisuudesta toimii ja Bob muotoilee viestin nyt näin:
> 🕹Uusi ilmaispeli Epic Games Storessa!
> 
> https://www.epicgames.com/store/en-US/p/daemon-x-machina

Seuraavaksi design-kysymyksiin.
Ehdotukseni on että tähän ilmaispeliin liittyen Bob itse lähettää viestin kerran viikossa torstai 10 am est, eli 17:00 Suomen aikaa, jälkeen.
Tämä voisi olla esimerkiksi torstaina illalla tai perjantaina aamulla.
Uuden pelin julkaisun lähekkyys perjantaihin kutsuu miettimään tulisiko ilmaispelistä ilmoituksen olla aina osa perjantain daily digestiä?
Kallistun tämän jälkimmäisen idean kannalle, sillä mielestäni Bobin pitäisi lähettää itse mahdollisimman vähän viestejä. Myöskään oma komento ilmaispelistä ilmoittamiseen ei tunnu järkevältä, sillä tarve sille on vain kerran viikossa.

**Comment by Kaehaerae** [comment]
Kannatan ilmoitusta pelistä osana perjantain digestiä!

**Comment by Latemus** [comment]
- Haetaan ajoitetusti aina torstaina tiedot api-endpointista: https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=en-US&country=FI&allowCountries=FI
- Alkuun vaikka botti laittaa yhdellä viestillä sen hetkisen tilanteen. Mukaan kuvat ja mahdollisuus laajentaa napista descriptionit näkyviin
- Myöhemmin sitten osaksi daily digestiä tms

**Comment by Latemus** [comment]
Botin viesti tulee olemaan suunnilleen:
![image](https://user-images.githubusercontent.com/13104473/214921392-7756971e-d05a-4e76-a85e-6f24bb93e458.png)
