### ISSUE TITLE
weather_command toivottuja muutoksia: tuulen nopeus ja suunta, tuntuu kuin

### ISSUE THREAD

**Issue by Kaehaerae** [M4R774/bobweb2#81]
weather_command-toiminnallisuuteen on toivottu seuraavia muutoksia: 

- tuulen nopeus ja suunta
- lämpötila, tuntuu kuin 
- ilmanpainetiedon poisto 

Mitä mieltä muut näistä? Jos ok, niin toteutusehdotus jo valmiina

**Comment by Kaehaerae** [comment]
Voisi näyttää esim seuraavalta:

Sää paikassa Helsinki:
Lämpötila °C = -4.4 (tuntuu kuin -9.3)
Tuuli m/s = 3.58 pohjoisesta
Ilmankosteus % = 86
Sään kuvaus = broken ☁

**Comment by matiasautio** [comment]
Onks ilmankosteus tarpeellinen? Toki on hauska nähdä jos se on tosi korkea tai tosi matala ("lol ilmankosteus 99%"), mutten muista ikinä miettineeni sitä irl.

**Comment by Kaehaerae** [comment]
Oisko ilmankosteuden tilalle auringonnousu-ja laskuajat? Sitä ainakin tulee mietittyä usein! 

https://openweathermap.org/current

sys.sunrise Sunrise time, unix, UTC
sys.sunset Sunset time, unix, UTC

**Comment by matiasautio** [comment]
imo paljon kiinnostavampi info tuo. Toisaalta toi vois myös olla jotakin mikä tulis Bobin daily digestiin, koska ei liity suoraan säätilaan.

**Comment by Kaehaerae** [comment]
Se kuulostaisi omaan korvaan hyvältä - ehdotin sitä nyt kyseiseen issueen (https://github.com/M4R774/bobweb2/issues/66). 

Eli säässä olisi vain seuraavat: 

Sää paikassa Helsinki:
Lämpötila °C = -4.4 (tuntuu kuin -9.3)
Tuuli m/s = 3.58 pohjoisesta
Sään kuvaus = broken ☁

jonka lisäksi daily digestive-keksissä olis auringonnousu-ja lasku bobilaisten sijaintien keskipisteestä?

**Comment by M4R774** [comment]
Oma ehdotus:

New York klo 17:30 (UTC-5)
-4.4 °C (tuntuu -9.3)
3.58 m/s pohjoisesta
broken ☁

**Comment by Kaehaerae** [comment]
Kellonaika aikavyöhykkeineen onkin hyvä. Näköjään tuosta saa myös maakoodin, jonka vois laittaa paikannimen perään. 

Voisin lähteä toteuttamaan seuraavaa: 
New York, US klo 17:30 (UTC-5)
-4.4 °C (tuntuu -9.3)
3.58 m/s pohjoisesta
broken ☁
